# Server Configuration
server.port=8082
spring.application.name=location-service

# Redis Grid Configuration
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:16379}

# Logging Settings
logging.level.com.uber.locationservice=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n
management.endpoints.web.exposure.include=health
management.endpoints.web.cors.allowed-origins=http://localhost:5173
management.endpoints.web.cors.allowed-methods=*
management.endpoints.web.cors.allowed-headers=*  
 